name: smartypy
dependencies:
  - python=3.5
  - setuptools
  - ipython
  - numpy>=1.8
  - pandas
  - scipy
  - matplotlib
  - numba
  - scikit-learn
  - scikit-image
  - jupyter
  - pytest

pip:
  - keras

# Should work cross platform...
# Install tensorflow https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#optional-setup-gpu-for-mac
#  conda install -c conda-forge tensorflow
#  pip install tflearn
