name: smartypy
dependencies:
  - python=3.5
  - setuptools
  - ipython
  - numpy>=1.8
  - pandas
  - scipy
  - matplotlib
  - numba
  - scikit-learn
  - jupyter
  - pytest

# Shoudl work cross platform...
