name: smartypy
dependencies:
  - python=3.5
  - numpy
  - pandas
  - scipy
  - astropy
  - matplotlib
  - numba
  - sklearn
  - pip:
    - poliastro
    - jupyter
    - spiceypy

# Shoudl work cross platform...
